### ISSUE TITLE
VCPKG upstream integration

### ISSUE THREAD

**Issue by SchaichAlonso** [silverqx/TinyORM#29]
microsoft/vcpkg#31087 is requesting to integrate tinyorm into upstream vcpkg's centralized ports repository.

I have prepared [a vcpkg fork](https://github.com/PurpleFlowerGarden/vcpkg/tree/2023.07.28-tinyorm/ports/tinyorm) which contains a tinyorm port deriving from [the overlay port that is part of TinyORM](https://github.com/silverqx/TinyORM/blob/1c444b595381fd4c14be87e6bf3ae4a7ba9c2a6c/cmake/vcpkg/ports/tinyorm) as well as a [TinyORM consumer project](https://github.com/PurpleFlowerGarden/TinyOrmOnboarding) that uses the tinyorm package generated with the vcpkg fork. It can run the simplistic test on all primary supported vcpkg platforms other then Mac OS X using [GitHub hosted runners](https://github.com/PurpleFlowerGarden/TinyORMOnboarding/actions).

The patches applied address
- [x] silverqx/TinyORM#21 via [0003-reduce-assert-scopes.patch](https://github.com/PurpleFlowerGarden/vcpkg/blob/459992a92f661736bd575e033e728493e52f8db5/ports/tinyorm/0003-reduce-assert-scopes.patch)
- [x]  silverqx/TinyORM#19 via [0001-install-tom.patch](https://github.com/PurpleFlowerGarden/vcpkg/blob/459992a92f661736bd575e033e728493e52f8db5/ports/tinyorm/0001-install-tom.patch)
- [x] silverqx/TinyORM#23 via [0002-comment.patch](https://github.com/PurpleFlowerGarden/vcpkg/blob/459992a92f661736bd575e033e728493e52f8db5/ports/tinyorm/0002-comment.patch)
- [x] silverqx/TinyORM#18 via [0004-remove-interface-warnings.patch](https://github.com/PurpleFlowerGarden/vcpkg/blob/459992a92f661736bd575e033e728493e52f8db5/ports/tinyorm/0004-remove-interface-warnings.patch)
- [x] silverqx/TinyORM#25 via [cmake/tiny_cmake_config_fixup.cmake](https://github.com/PurpleFlowerGarden/vcpkg/blob/459992a92f661736bd575e033e728493e52f8db5/ports/tinyorm/cmake/tiny_cmake_config_fixup.cmake) (not really a patch)

Further, I modified the microsoft CI ruleset [to assert](https://github.com/PurpleFlowerGarden/vcpkg/blob/2023.07.28-tinyorm/scripts/ci.baseline.txt#L1296)  Mac OS X builds fail ( silverqx/TinyORM#28 ). However I'm not sure what to do about the other targets blacklisted in [vcpkg.json:9](https://github.com/PurpleFlowerGarden/vcpkg/blob/459992a92f661736bd575e033e728493e52f8db5/ports/tinyorm/vcpkg.json#L9) (which is copy-pasted from [the manifest variant's same line](https://github.com/silverqx/TinyORM/blob/1c444b595381fd4c14be87e6bf3ae4a7ba9c2a6c/cmake/vcpkg/ports/tinyorm/vcpkg.json#L9)). Are these platforms known not to work, or just untested?

**Comment by silverqx** [comment]
Nice, I wanted to post these vcpkg ports into the vcpkg central repo but I still couldn't find enough time for it. 🙂

You did a great job on this. Nice to see. I'm gonna address these patches so we can entirely remove them.

> [Insufficiently escaped comment in tinytypes.hpp #23](https://github.com/silverqx/TinyORM/issues/23) via [0002-comment.patch](https://github.com/PurpleFlowerGarden/vcpkg/blob/459992a92f661736bd575e033e728493e52f8db5/ports/tinyorm/0002-comment.patch)

I also removed this comment because it's not relevant anymore, it was left there after refactoring. I spent a few minutes on this yesterday.

I have done the `qmake` refactor so now I can spend time on this.

**Comment by silverqx** [comment]
I think everything is fixed and all patches can be removed (still not merged to the main branch, will be in the next release).

Also, I would **wait** a while before finally posting it to the `vcpkg` repo to test it correctly, I haven't tried all scenarios yet like Linux and MSYS2 shared and static builds.

**Comment by silverqx** [comment]
Great progress today, I have finished `CI` for vcpkg ports to correctly support them [here](https://github.com/silverqx/TinyORM/commit/d332258b342089985cd0c069bbd6bdf2f0032ba4).

**Comment by silverqx** [comment]
I have it done, I had to move `CI` for `vcpkg` to __self-hosted__ runners also with `Clang-tidy` and `Clazy` analyzers because they took too many minutes, 3 runs took me more than 1000 minutes from 2000 minutes (which are for free) and that is a lot, I was out of minutes last month after one deploy 🙃🫤

The currently deployed TinyORM `v0.36.0` is ready to be merged to the vcpkg repo, can you invoke your workflows and also test it? If there are any other bugs or problems? @SchaichAlonso

**Comment by silverqx** [comment]
Also, how are running your workflows? Any fails? @SchaichAlonso

**Comment by silverqx** [comment]
I have created PR at microsoft/vcpkg#34640, also a new release was pushed today v0.36.2.

**Comment by SchaichAlonso** [comment]
> Also, how are running your workflows? Any fails? @SchaichAlonso

[all buildsystems can build the consumer](https://github.com/PurpleFlowerGarden/TinyORMOnboarding/actions/runs/6591537534), though I only used tinyorm-0.35.0, as I haven't updated the port yet.

I noticed, though, that passisng `-DORM=Off -DTOM=Off -DTOM_EXAMPLE=Off` to cmake causes the setup logic to emit a diagnositc confirming the 3 were disabled, but then installing `orm/tiny/model.hpp` nevertheless.

**Comment by silverqx** [comment]
> I noticed, though, that passisng -DORM=Off -DTOM=Off -DTOM_EXAMPLE=Off to cmake causes the setup logic to emit a diagnositc confirming the 3 were disabled, but then installing orm/tiny/model.hpp nevertheless.

I will check it if I can find something.

Sry, I accidentally edited your reply 😂

**Comment by silverqx** [comment]
> [all buildsystems can build the consumer](https://github.com/PurpleFlowerGarden/TinyORMOnboarding/actions/runs/6591537534), though I only used tinyorm-0.35.0, as I haven't updated the port yet.

This is good, there are minimal changes in later releases.

**Comment by silverqx** [comment]
> I noticed, though, that passisng -DORM=Off -DTOM=Off -DTOM_EXAMPLE=Off to cmake causes the setup logic to emit a diagnositc confirming the 3 were disabled, but then installing orm/tiny/model.hpp nevertheless.

I tried now and can't reproduce it, I tried single-config debug build and install. The code responsible is [here](https://github.com/silverqx/TinyORM/blob/main/cmake/Modules/TinyDeployment.cmake#L61-L71) it can't install.

What was your config., single-config, multi, vcpkg install?

**Comment by SchaichAlonso** [comment]
> What was your config., single-config, multi, vcpkg install?

vcpkg's cmake-ninja default setup:

```

-- The following features have been disabled:

 * BUILD_SHARED_LIBS, Build using shared libraries (default: ON)
 * BUILD_TESTS, Build TinyORM unit tests (default: OFF)
 * MSVC_RUNTIME_DYNAMIC, Use MSVC dynamic runtime library (-MD) instead of static (-MT), also considers a Debug configuration (-MTd, -MDd) (default: ON; depends on condition: MSVC;NOT DEFINED CMAKE_MSVC_RUNTIME_LIBRARY)
 * MYSQL_PING, Enable MySQL ping on Orm::MySqlConnection
 * DISABLE_THREAD_LOCAL, Remove all the thread_local storage duration specifiers (disables threading support)
 * ORM, Controls the compilation of all ORM-related source code, when this option is disabled, then only the query builder without ORM is compiled.
 * TOM, Controls the compilation of all tom related source code (command line interface).
 * TOM_EXAMPLE, Build the tom command-line application example (default: OFF; depends on condition: TOM)
```
```
-- Installing: /home/alonso/projects/Bougainvillea/vcpkg/packages/tinyorm_x64-freebsd/include/orm/tiny/relations/relationproxies.hpp
-- Installing: /home/alonso/projects/Bougainvillea/vcpkg/packages/tinyorm_x64-freebsd/include/orm/tiny/model.hpp
-- Installing: /home/alonso/projects/Bougainvillea/vcpkg/packages/tinyorm_x64-freebsd/include/orm/macros
```

[config-x64-freebsd-out.log](https://github.com/silverqx/TinyORM/files/13058484/config-x64-freebsd-out.log)
[install-x64-freebsd-rel-out.log](https://github.com/silverqx/TinyORM/files/13058483/install-x64-freebsd-rel-out.log)

Corresponding windows OS build logs can be obtained from the [buildlogs](https://github.com/PurpleFlowerGarden/TinyORMOnboarding/suites/17462979498/artifacts/998167044) artifact evaluated by github actions.

**Comment by silverqx** [comment]
> cmake-ninja default setup

You mean `"default-features": false` in `vcpkg.json` file and in manifest mode?

**Comment by silverqx** [comment]
Because orm is enabled in default features [here](https://github.com/silverqx/TinyORM/blob/main/cmake/vcpkg/ports/tinyorm/vcpkg.json#L31)

**Comment by SchaichAlonso** [comment]
> > cmake-ninja default setup
> 
> You mean `"default-features": false` in `vcpkg.json` file and in manifest mode?

Yes.

A cmake invokation by VCPKG might fail to pass the correct options to tinyorm due to bugs in the portfile or vcpkg logic, but tinyorm's cmake should be consistent between it's diagnostic and the installed features.

**Comment by silverqx** [comment]
I check it tomorrow, these features are reported by [`feature_summary()`](https://cmake.org/cmake/help/latest/module/FeatureSummary.html) module and function.

**Comment by silverqx** [comment]
But vcpkg and default-features it already sounds like a pain 😂 and I haven't even started testing 😎 and you can double this feeling in manifest mode

**Comment by SchaichAlonso** [comment]
The port from microsoft/vcpkg#34640 can provision a TinyORM that works with all build systems [here](https://github.com/PurpleFlowerGarden/TinyORMOnboarding/actions/runs/6594235351), though I [suppressed the unsupported statement of the portfile](https://github.com/PurpleFlowerGarden/TinyORMOnboarding/commit/a727f95b1a52f7fb8d80fb7d3811a0d023409495).

The issue with the header file seems to persist.

**Comment by silverqx** [comment]
> The issue with the header file seems to persist.

With which header file? I don't remember any issue with a header file.

**Comment by silverqx** [comment]
> > You mean `"default-features": false` in `vcpkg.json` file and in manifest mode?
> 
> Yes.

Now I tried it and can't reproduce it, tried with [HelloWorld](https://github.com/silverqx/TinyORM-HelloWorld) example app. and this [vcpkg.json](https://github.com/silverqx/TinyORM-HelloWorld/blob/main/vcpkg.json.VcpkgManifest.Qt6.example#L15), I also removed this [line](https://github.com/silverqx/TinyORM-HelloWorld/blob/main/vcpkg.json.VcpkgManifest.Qt6.example#L16) from vcpkg.json.

Then looked inside the build folder `HelloWorld-builds-cmake\build-debug\vcpkg_installed\x64-windows\include\orm` and the `ORM` header files __are not__ there, also the `tom` header files are not installed.

Looked also into the `buildtrees\tinyorm\install-x64-windows-dbg-out.log` and looks correct too:

```
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/debug/lib/TinyOrm0d.lib
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/debug/bin/TinyOrm0d.dll
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/debug/share/tinyorm/TinyOrmTargets.cmake
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/debug/share/tinyorm/TinyOrmTargets-debug.cmake
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/debug/bin/TinyOrm0d.pdb
```

And the following for the release install `buildtrees\tinyorm\install-x64-windows-rel-out.log`:

<details>
  <summary>install-x64-windows-rel-out.log</summary>

```
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/lib/TinyOrm0.lib
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/bin/TinyOrm0.dll
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/share/tinyorm/TinyOrmTargets.cmake
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/share/tinyorm/TinyOrmTargets-release.cmake
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/bin/TinyOrm0.pdb
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/basegrammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/concerns
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/concerns/countsqueries.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/concerns/detectslostconnections.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/concerns/explainqueries.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/concerns/hasconnectionresolver.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/concerns/logsqueries.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/concerns/managestransactions.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/concerns/parsessearchpath.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/config.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/configurations
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/configurations/configurationoptionsparser.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/configurations/configurationparser.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/configurations/configurationparserfactory.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/configurations/configurationparserinterface.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/configurations/mysqlconfigurationparser.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/configurations/postgresconfigurationparser.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/configurations/sqliteconfigurationparser.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/connectionresolverinterface.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/connectors
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/connectors/connectionfactory.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/connectors/connector.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/connectors/connectorinterface.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/connectors/mysqlconnector.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/connectors/postgresconnector.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/connectors/sqliteconnector.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/constants.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/constants_extern.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/constants_inline.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/databaseconnection.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/databasemanager.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/db.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/domainerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/invalidargumenterror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/invalidformaterror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/invalidtemplateargumenterror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/logicerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/lostconnectionerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/multiplecolumnsselectederror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/multiplerecordsfounderror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/ormerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/queryerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/recordsnotfounderror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/runtimeerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/searchpathemptyerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/sqlerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/sqlitedatabasedoesnotexisterror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/exceptions/sqltransactionerror.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/libraryinfo.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/archdetect.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/commonnamespace.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/compilerdetect.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/export.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/export_common.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/likely.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/logexecutedquery.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/systemheader.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/macros/threadlocal.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/mysqlconnection.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/ormconcepts.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/ormtypes.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/postgresconnection.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/concerns
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/concerns/buildsqueries.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/expression.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/grammars
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/grammars/grammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/grammars/mysqlgrammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/grammars/postgresgrammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/grammars/sqlitegrammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/joinclause.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/processors
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/processors/mysqlprocessor.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/processors/postgresprocessor.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/processors/processor.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/processors/sqliteprocessor.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/query/querybuilder.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/blueprint.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/columndefinition.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/columndefinitionreference.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/foreignidcolumndefinitionreference.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/foreignkeydefinitionreference.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/grammars
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/grammars/mysqlschemagrammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/grammars/postgresschemagrammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/grammars/schemagrammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/grammars/sqliteschemagrammar.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/indexdefinitionreference.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/mysqlschemabuilder.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/postgresschemabuilder.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/schemabuilder.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/schemaconstants.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/schemaconstants_extern.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/schemaconstants_inline.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/schematypes.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema/sqliteschemabuilder.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/schema.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/sqliteconnection.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/support
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/support/databaseconfiguration.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/support/databaseconnectionsmap.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/types
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/types/log.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/types/sqlquery.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/types/statementscounter.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/configuration.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/container.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/fs.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/helpers.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/notnull.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/nullvariant.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/query.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/string.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/thread.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/utils/type.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/include/orm/version.hpp
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/share/tinyorm/copyright
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/share/tinyorm/usage
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/share/tinyorm/Modules/TinyPackageConfigHelpers.cmake
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/share/tinyorm/TinyOrmConfig.cmake
-- Installing: O:/Code/c_libs/vcpkg/packages/tinyorm_x64-windows/share/tinyorm/TinyOrmConfigVersion.cmake
```

</details>

**Comment by silverqx** [comment]
I forgot, I also tried vcpkg classic mode like `vcpkg install tinyorm[core]` and also can't reproduce.
